version: '3'

services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./app:/app
        depends_on:
            - php

    php:
        build:
            context: .
            dockerfile: Dockerfile
        env_file: env/php.env
        volumes:
            - ./app:/app
        expose:
            - "9000"

    mysql:
        image: mariadb:10.6.5
        env_file: env/mariadb.env
        volumes:
            - mysqldata:/var/lib/mysql
            - ./sql:/docker-entrypoint-initdb.d
        ports:
            - "3306:3306"

    phpmyadmin:
        image: phpmyadmin:latest
        ports:
            - "8080:80"
        environment:
            - PMA_HOST=mysql

volumes:
    mysqldata: