version: '3'

services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./app:/app
        networks:
            - nginxphp
        environment:
            - PORT=80

    php:
        build:
            context: .
            dockerfile: PHP.Dockerfile
        env_file: env/php.env
        volumes:
            - ./app:/app
        networks:
            - nginxphp
        expose:
            - "9000"

    mysql:
        image: mariadb:10.6.5
        env_file: env/mariadb.env
        volumes:
            - mysqldata:/var/lib/mysql
            - ./sql:/docker-entrypoint-initdb.d
        ports:
            - "3306:3306"
        networks:
            - nginxphp

    phpmyadmin:
        image: phpmyadmin:latest
        ports:
            - "8080:80"
        environment:
            - PMA_HOST=mysql
        networks:
            - nginxphp

volumes:
    mysqldata: {}

networks:
    nginxphp:
